analyzer:
  exclude:
    - build/**
    - android/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    always_declare_return_types: true
    prefer_final_fields: true
